### ISSUE TITLE
search a text file of rsids

### ISSUE THREAD

**Issue by stephenturner** [bioforensics/rsidx#1]
Nice! I had written something similar myself but not as efficient. How might one most easily search a text file of RSIDs, perhaps on a pipe, or using `<` or otherwise? Thanks!

**Comment by zoeward-nz** [comment]
Hi, is it possible to input a text file of rsIDs?

**Comment by standage** [comment]
Hi, at the moment it is only possible through process substitution.

```
rsidx search dbSNP.vcf.gz dbSNP.rsidx <(cat ids.txt)
```

This should work for dozens and maybe even hundreds of rsids, but at some point you may run into operating system limits for number of characters/arguments in a command.

It will be straightforward to implement support for this feature. I will plan to do so some time this week, and post a new version to bioconda.

**Comment by standage** [comment]
With #7 merged, you can now do the following from the latest master.

```
rsidx search dbSNP.vcf.gz dbSNP.rsidx --file ids.txt
```

Will post to bioconda soon.*

**Comment by standage** [comment]
rsidx version 0.3 with the new `--file` flag is [now available from bioconda](https://github.com/bioconda/bioconda-recipes/pull/34195).

**Comment by zoeward-nz** [comment]
Hi Daniel,

I removed my previous conda rsidx env and re-installed (conda install -c
bioconda rsidx) but the version is saying 0.2 still not 0.3?

**Comment by standage** [comment]
Does it work if you do `conda install -c bioconda rsidx=0.3`?

**Comment by zoeward-nz** [comment]
This worked. Thanks alot!
